"""Generate OOKc pressure/horizontal/vertical velocity acceptance artifacts."""

from __future__ import annotations

import argparse
import csv
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from for_test.plot_propagation_loss_comparison import (
    discover_cases,
    file_record,
    process_cases,
    run_logged_command,
    stage_case_inputs,
)
from for_test.shd_reader import ShadeFile, read_shade_file
from for_test.velocity_analysis import (
    assert_matching_shade_grids,
    compute_velocity_slice_metrics,
    reshape_shade,
    tl_db,
)


OUTPUT_MARKER = ".ookc_velocity_comparison_output"


def discover_velocity_cases(test_dir: Path):
    return discover_cases(Path(test_dir))


def velocity_figure_name(
    case_name: str, source_index: int, source_depth_m: float
) -> str:
    depth_token = f"{source_depth_m:g}".replace(".", "p")
    return f"{case_name}_src{source_index}_sd{depth_token}m.png"


def safe_reset_velocity_output(output_dir: Path, workspace: Path) -> None:
    """Replace only an output directory owned by this script."""

    output = Path(output_dir).resolve()
    workspace = Path(workspace).resolve()
    forbidden = {Path(output.anchor), workspace, (workspace / "test").resolve()}
    try:
        output.relative_to(workspace)
    except ValueError as error:
        raise ValueError(f"unsafe output directory: {output}") from error
    if output in forbidden:
        raise ValueError(f"unsafe output directory: {output}")
    if output.exists():
        if not (output / OUTPUT_MARKER).is_file():
            raise ValueError(
                "refusing to replace output without ownership marker: "
                f"{output}"
            )
        shutil.rmtree(output)
    output.mkdir(parents=True)
    (output / OUTPUT_MARKER).write_text(
        "Generated by plot_velocity_comparison.py\n", encoding="utf-8"
    )


def velocity_manifest_payload(
    case_records: list[dict], rows: list[dict]
) -> dict:
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "case_count": len(case_records),
        "successful_case_count": sum(
            record.get("status") == "success" for record in case_records
        ),
        "source_slice_count": sum(
            int(record.get("source_count", 0)) for record in case_records
        ),
        "successful_source_slice_count": len(rows),
        "cases": case_records,
        "metrics": rows,
    }


def _stats_fields(prefix: str, stats) -> dict:
    return {
        f"{prefix}_valid_points": stats.valid_points,
        f"{prefix}_correlation": stats.correlation,
        f"{prefix}_mean_abs_delta_db": stats.mean_abs_delta_db,
        f"{prefix}_p50_abs_delta_db": stats.p50_abs_delta_db,
        f"{prefix}_p90_abs_delta_db": stats.p90_abs_delta_db,
        f"{prefix}_p95_abs_delta_db": stats.p95_abs_delta_db,
        f"{prefix}_p98_abs_delta_db": stats.p98_abs_delta_db,
        f"{prefix}_max_abs_delta_db": stats.max_abs_delta_db,
    }


def _surface_fields(prefix: str, surface) -> dict:
    return {
        f"{prefix}_has_surface_row": surface.has_surface_row,
        f"{prefix}_surface_depth_m": surface.surface_depth_m,
        f"{prefix}_surface_max_abs": surface.surface_max_abs,
        f"{prefix}_global_max_abs": surface.global_max_abs,
        f"{prefix}_surface_to_global_max_ratio": (
            surface.surface_to_global_max_ratio
        ),
        f"{prefix}_first_interior_to_global_max_ratio": (
            surface.first_interior_to_global_max_ratio
        ),
        f"{prefix}_surface_is_near_zero": surface.is_near_zero,
    }


def analyze_velocity_shades(
    case_name: str,
    pressure: ShadeFile,
    horizontal: ShadeFile,
    vertical: ShadeFile,
) -> list[dict]:
    assert_matching_shade_grids(pressure, horizontal, vertical)
    pressure_cube = reshape_shade(pressure)
    horizontal_cube = reshape_shade(horizontal)
    vertical_cube = reshape_shade(vertical)
    rows = []
    for source_index, source_depth in enumerate(pressure.source_depths):
        metrics = compute_velocity_slice_metrics(
            pressure_cube[source_index],
            horizontal_cube[source_index],
            vertical_cube[source_index],
            receiver_depths=pressure.receiver_depths,
            ranges_metres=pressure.ranges_metres,
            source_depth=float(source_depth),
        )
        row = {
            "case": case_name,
            "frequency_hz": float(pressure.frequency),
            "source_index": source_index,
            "source_depth_m": float(source_depth),
            "line_receiver_depth_m": metrics.line_receiver_depth_m,
            "interior_point_count": metrics.interior_point_count,
            "rescaled_horizontal_p50_abs_delta_db": (
                metrics.rescaled_horizontal_p50_abs_delta_db
            ),
            **_stats_fields(
                "ph_interior", metrics.pressure_horizontal_interior
            ),
            **_stats_fields(
                "ph_source_line", metrics.pressure_horizontal_source_line
            ),
            **_stats_fields("pv_interior", metrics.pressure_vertical_interior),
            **_surface_fields("pressure", metrics.pressure_surface),
            **_surface_fields("horizontal", metrics.horizontal_surface),
            **_surface_fields("vertical", metrics.vertical_surface),
        }
        rows.append(row)
    return rows


def _interior_axes(shade: ShadeFile) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    depths = np.asarray(shade.receiver_depths, dtype=float)
    ranges = np.asarray(shade.ranges_metres, dtype=float)
    depth_mask = np.ones(depths.size, dtype=bool)
    if depths.size and np.isclose(depths[0], 0.0, atol=1.0e-8, rtol=0.0):
        depth_mask[0] = False
    range_mask = ranges > 0.0
    if not np.any(depth_mask) or not np.any(range_mask):
        raise ValueError("no interior positive-range grid available for plotting")
    return depths[depth_mask], ranges[range_mask] / 1000.0, np.ix_(depth_mask, range_mask)


def _robust_limits(*arrays: np.ndarray) -> tuple[float, float]:
    finite = np.concatenate(
        [np.asarray(array)[np.isfinite(array)].ravel() for array in arrays]
    )
    if finite.size == 0:
        return 0.0, 1.0
    low, high = np.percentile(finite, [2.0, 98.0])
    if not np.isfinite(low) or not np.isfinite(high) or high <= low:
        low, high = float(np.min(finite)), float(np.max(finite) + 1.0)
    return float(low), float(high)


def plot_velocity_slice(
    case_name: str,
    pressure: ShadeFile,
    horizontal: ShadeFile,
    vertical: ShadeFile,
    source_index: int,
    row: dict,
    path: Path,
) -> None:
    p = reshape_shade(pressure)[source_index]
    h = reshape_shade(horizontal)[source_index]
    v = reshape_shade(vertical)[source_index]
    depths, ranges_km, index = _interior_axes(pressure)
    p_tl, h_tl, v_tl = tl_db(p)[index], tl_db(h)[index], tl_db(v)[index]
    ph_low, ph_high = _robust_limits(p_tl, h_tl)
    v_low, v_high = _robust_limits(v_tl)
    extent = [ranges_km[0], ranges_km[-1], depths[-1], depths[0]]

    fig, axes = plt.subplots(2, 3, figsize=(16, 9), constrained_layout=True)
    panels = (
        (axes[0, 0], p_tl, "TL(P): pressure", ph_low, ph_high, "viridis"),
        (axes[0, 1], h_tl, "TL(H): equivalent horizontal velocity", ph_low, ph_high, "viridis"),
        (axes[0, 2], v_tl, "TL(V): equivalent vertical velocity", v_low, v_high, "viridis"),
    )
    for axis, values, title, low, high, colour in panels:
        image = axis.imshow(
            values,
            extent=extent,
            aspect="auto",
            cmap=colour,
            vmin=low,
            vmax=high,
        )
        axis.set_title(title)
        axis.set_xlabel("Range (km)")
        axis.set_ylabel("Receiver depth (m)")
        fig.colorbar(image, ax=axis, label="dB")

    difference = h_tl - p_tl
    delta_limit = max(float(np.nanpercentile(np.abs(difference), 98.0)), 0.1)
    image = axes[1, 0].imshow(
        difference,
        extent=extent,
        aspect="auto",
        cmap="coolwarm",
        vmin=-delta_limit,
        vmax=delta_limit,
    )
    axes[1, 0].set_title("TL(H) - TL(P), interior only")
    axes[1, 0].set_xlabel("Range (km)")
    axes[1, 0].set_ylabel("Receiver depth (m)")
    fig.colorbar(image, ax=axes[1, 0], label="dB")

    receiver_depths = np.asarray(pressure.receiver_depths, dtype=float)
    line_index = int(
        np.argmin(np.abs(receiver_depths - row["source_depth_m"]))
    )
    positive = np.asarray(pressure.ranges_metres, dtype=float) > 0.0
    full_ranges = np.asarray(pressure.ranges_metres, dtype=float)[positive] / 1000.0
    axes[1, 1].plot(full_ranges, tl_db(p)[line_index, positive], label="P", lw=1.2)
    axes[1, 1].plot(full_ranges, tl_db(h)[line_index, positive], label="H", lw=1.0)
    axes[1, 1].plot(full_ranges, tl_db(v)[line_index, positive], label="V", lw=1.0, alpha=0.8)
    axes[1, 1].invert_yaxis()
    axes[1, 1].grid(alpha=0.25)
    axes[1, 1].legend()
    axes[1, 1].set_title(f"Nearest source-depth line: {row['line_receiver_depth_m']:g} m")
    axes[1, 1].set_xlabel("Range (km)")
    axes[1, 1].set_ylabel("TL (dB)")

    axis = axes[1, 2]
    labels = ["P surface", "H surface", "V surface"]
    ratios = [
        row["pressure_surface_to_global_max_ratio"],
        row["horizontal_surface_to_global_max_ratio"],
        row["vertical_surface_to_global_max_ratio"],
    ]
    plotted = [
        max(float(value), 1.0e-16)
        if value is not None and np.isfinite(value)
        else 1.0e-16
        for value in ratios
    ]
    axis.bar(labels, plotted, color=["#4c78a8", "#f58518", "#54a24b"])
    axis.set_yscale("log")
    axis.set_ylim(1.0e-16, 2.0)
    axis.set_ylabel("surface max / global max")
    axis.set_title("Surface-boundary diagnostic (excluded above)")
    axis.grid(axis="y", alpha=0.25)
    for number, value in enumerate(ratios):
        text = "n/a" if value is None else f"{value:.2e}"
        axis.text(number, plotted[number] * 1.5, text, ha="center", fontsize=8)

    fig.suptitle(
        f"{case_name} | f={row['frequency_hz']:g} Hz | source={row['source_depth_m']:g} m\n"
        f"P-H interior: corr={row['ph_interior_correlation']:.5f}, "
        f"P50={row['ph_interior_p50_abs_delta_db']:.3f} dB, "
        f"P95={row['ph_interior_p95_abs_delta_db']:.3f} dB; "
        f"diagnostic extra rho*c0 P50={row['rescaled_horizontal_p50_abs_delta_db']:.2f} dB",
        fontsize=12,
    )
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)


def run_velocity_case(case, runner: Path, output: Path, threads: int) -> dict:
    run_dir = Path(output) / "runs" / case.name
    inputs = stage_case_inputs(case, run_dir)
    output_root = run_dir / case.name
    record = {
        "case": case.name,
        "status": "velocity_failed",
        "source_count": 0,
        "executable": file_record(runner),
        "inputs": inputs,
        "runs": {},
        "outputs": {},
        "metrics": [],
        "figures": [],
    }
    record["runs"]["velocity"] = run_logged_command(
        [runner, run_dir / f"{case.name}.env", output_root, str(threads)],
        run_dir,
        "velocity",
    )
    if record["runs"]["velocity"]["returncode"] != 0:
        record["error"] = "OOKc velocity calculation failed; inspect velocity.stderr.log"
        return record

    paths = {
        "pressure_shd": Path(f"{output_root}_P.shd"),
        "horizontal_shd": Path(f"{output_root}_H.shd"),
        "vertical_shd": Path(f"{output_root}_V.shd"),
        "pressure_mod": Path(f"{output_root}_P.mod"),
    }
    for name, path in paths.items():
        if not path.is_file():
            record["error"] = f"velocity output is missing: {path.name}"
            return record
        record["outputs"][name] = file_record(path)

    try:
        pressure = read_shade_file(paths["pressure_shd"])
        horizontal = read_shade_file(paths["horizontal_shd"])
        vertical = read_shade_file(paths["vertical_shd"])
        rows = analyze_velocity_shades(case.name, pressure, horizontal, vertical)
        record["source_count"] = len(rows)
        for row in rows:
            figure = Path(output) / "figures" / velocity_figure_name(
                case.name, row["source_index"], row["source_depth_m"]
            )
            plot_velocity_slice(
                case.name,
                pressure,
                horizontal,
                vertical,
                row["source_index"],
                row,
                figure,
            )
            row["figure"] = str(figure.relative_to(output)).replace("\\", "/")
            record["figures"].append(file_record(figure))
        record["metrics"] = rows
        record["status"] = "success"
    except Exception as error:
        record["status"] = "analysis_failed"
        record["error"] = str(error)
    return record


def write_velocity_metrics(rows: list[dict], path: Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = list(rows[0]) if rows else ["case"]
    with path.open("w", encoding="utf-8-sig", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def create_velocity_overview(rows: list[dict], path: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(15, 10), constrained_layout=True)
    if not rows:
        for axis in axes.ravel():
            axis.axis("off")
        axes[0, 0].text(0.5, 0.5, "No successful velocity results", ha="center")
    else:
        labels = [
            f"{row['case']}\n{row['source_depth_m']:g}m" for row in rows
        ]
        x = np.arange(len(rows))
        p50 = [row["ph_interior_p50_abs_delta_db"] for row in rows]
        p95 = [row["ph_interior_p95_abs_delta_db"] for row in rows]
        corr = [row["ph_interior_correlation"] for row in rows]
        pv = [row["pv_interior_p50_abs_delta_db"] for row in rows]
        rescaled = [row["rescaled_horizontal_p50_abs_delta_db"] for row in rows]
        axes[0, 0].bar(x - 0.2, p50, width=0.4, label="P50")
        axes[0, 0].bar(x + 0.2, p95, width=0.4, label="P95")
        axes[0, 0].set_ylabel("|TL(H)-TL(P)| (dB)")
        axes[0, 0].set_title("Primary P-H interior difference")
        axes[0, 0].legend()
        axes[0, 1].plot(x, corr, "o-")
        axes[0, 1].set_ylim(-1.05, 1.05)
        axes[0, 1].set_ylabel("correlation")
        axes[0, 1].set_title("P-H interior TL correlation")
        axes[1, 0].bar(x, pv, color="#54a24b")
        axes[1, 0].set_ylabel("P50 |TL(V)-TL(P)| (dB)")
        axes[1, 0].set_title("P-V structural difference (diagnostic)")
        axes[1, 1].bar(x, rescaled, color="#e45756")
        axes[1, 1].set_ylabel("P50 difference (dB)")
        axes[1, 1].set_title("Incorrect repeated rho*c0 scaling diagnostic")
        for axis in axes.ravel():
            axis.grid(axis="y", alpha=0.25)
            axis.set_xticks(x)
            axis.set_xticklabels(labels, rotation=75, ha="right", fontsize=7)
    fig.suptitle("OOKc pressure / equivalent particle-velocity comparison")
    fig.savefig(path, dpi=160)
    plt.close(fig)


def write_velocity_analysis(
    records: list[dict], rows: list[dict], path: Path
) -> None:
    failures = [record for record in records if record.get("status") != "success"]
    lines = [
        "# OOKc 振速对比分析",
        "",
        (
            f"共发现 {len(records)} 个环境，成功 {len(records) - len(failures)} 个；"
            f"实际生成并分析 {len(rows)} 个声源切片。主统计均排除海面 z=0 行和 r=0 列。"
        ),
        "",
        "## 判据说明",
        "",
        "- KrakenC 作为压力/传播损失基准，不直接输出振速。OOKc 的 `_H.shd` 与 `_V.shd` 已分别按 `rho*c0*Vr`、`rho*c0*Vz` 导出，因此可直接与压力 P 的 TL 对比。",
        "- P-H 的相关系数、绝对差 P50/P95 是主要一致性指标；P-V 受波导结构和边界条件影响，仅作结构性诊断。",
        "- 再次乘 `rho*c0` 的结果仅用于量纲误用诊断，不进入结论。海面行单独报告，不进入主统计。",
        "",
        "## 全量结果",
        "",
        "| 环境 | 声源深度(m) | P-H相关系数 | P-H P50(dB) | P-H P95(dB) | P-V P50(dB) | 表面P/H/V比值 |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        surfaces = "/".join(
            "n/a"
            if row[f"{name}_surface_to_global_max_ratio"] is None
            else f"{row[f'{name}_surface_to_global_max_ratio']:.2e}"
            for name in ("pressure", "horizontal", "vertical")
        )
        lines.append(
            f"| {row['case']} | {row['source_depth_m']:.3g} | "
            f"{row['ph_interior_correlation']:.6f} | "
            f"{row['ph_interior_p50_abs_delta_db']:.3f} | "
            f"{row['ph_interior_p95_abs_delta_db']:.3f} | "
            f"{row['pv_interior_p50_abs_delta_db']:.3f} | {surfaces} |"
        )
    if rows:
        p50_values = np.asarray(
            [row["ph_interior_p50_abs_delta_db"] for row in rows], dtype=float
        )
        p95_values = np.asarray(
            [row["ph_interior_p95_abs_delta_db"] for row in rows], dtype=float
        )
        correlations = np.asarray(
            [row["ph_interior_correlation"] for row in rows], dtype=float
        )
        worst = sorted(
            rows,
            key=lambda row: row["ph_interior_p95_abs_delta_db"],
            reverse=True,
        )[:5]
        lines.extend(
            [
                "",
                "## 汇总结论",
                "",
                f"- 全部切片 P-H P50 中位数为 {np.nanmedian(p50_values):.3f} dB，P95 中位数为 {np.nanmedian(p95_values):.3f} dB。",
                f"- P-H 相关系数中位数为 {np.nanmedian(correlations):.6f}，最小值为 {np.nanmin(correlations):.6f}。",
                "- P-H P95 最大的 5 个切片："
                + "、".join(
                    f"{row['case']}(sd={row['source_depth_m']:g} m, {row['ph_interior_p95_abs_delta_db']:.3f} dB)"
                    for row in worst
                )
                + "。",
                "- 每个切片的六联图位于 `figures/`；总体对比见 [overview.png](overview.png)。",
            ]
        )
    if failures:
        lines.extend(["", "## 失败环境", ""])
        for record in failures:
            lines.append(
                f"- {record['case']}: {record.get('status')} — {record.get('error', 'unknown error')}"
            )
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _validate_executable(parser: argparse.ArgumentParser, path: Path) -> Path:
    resolved = path.resolve()
    if not resolved.is_file():
        parser.error(f"executable does not exist: {resolved}")
    return resolved


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate OOKc pressure/equivalent-velocity comparisons"
    )
    parser.add_argument("--test-dir", required=True, type=Path)
    parser.add_argument("--runner", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--threads", type=int, default=1)
    args = parser.parse_args()
    test_dir = args.test_dir.resolve()
    if not test_dir.is_dir():
        parser.error(f"test directory does not exist: {test_dir}")
    if args.threads < 1:
        parser.error("--threads must be at least 1")
    runner = _validate_executable(parser, args.runner)
    output = args.output.resolve()
    safe_reset_velocity_output(output, test_dir.parent)
    (output / "figures").mkdir()
    cases = discover_velocity_cases(test_dir)
    records = process_cases(
        cases,
        lambda case: run_velocity_case(case, runner, output, args.threads),
    )
    rows = [row for record in records for row in record.get("metrics", [])]
    write_velocity_metrics(rows, output / "metrics.csv")
    create_velocity_overview(rows, output / "overview.png")
    write_velocity_analysis(records, rows, output / "analysis.md")
    payload = velocity_manifest_payload(records, rows)
    (output / "manifest.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, allow_nan=False),
        encoding="utf-8",
    )
    passes = all(record.get("status") == "success" for record in records)
    print(
        json.dumps(
            {
                "passes": passes,
                "case_count": len(records),
                "source_slice_count": payload["source_slice_count"],
                "successful_source_slice_count": len(rows),
                "output": str(output),
            },
            ensure_ascii=False,
        )
    )
    return 0 if passes else 1


if __name__ == "__main__":
    raise SystemExit(main())
