from typing import Any, Sequence, overload
import numpy as np

class ThreadPool:
    def __init__(self, threads: int) -> None: ...

class SSP_Mode:
    MODE_N_n2Linear: SSP_Mode
    MODE_C_cLinear: SSP_Mode
    MODE_P_cPCHIP: SSP_Mode
    MODE_S_cCubic: SSP_Mode
    MODE_A_Analytic: SSP_Mode

class Media_Mode:
    MODE_A_Acoustic: Media_Mode
    MODE_E_Elastic: Media_Mode

class AttenuationUnit:
    MODE_F_dB_per_m_kHz: AttenuationUnit
    MODE_L_params_lose: AttenuationUnit
    MODE_M_dB_per_m: AttenuationUnit
    MODE_m_dB_per_m: AttenuationUnit
    MODE_N_Nepers_per_m: AttenuationUnit
    MODE_Q_Quality_Factor: AttenuationUnit
    MODE_W_db_per_lambda: AttenuationUnit

class OceanAbsorptionModel:
    None_: OceanAbsorptionModel
    Thorpe: OceanAbsorptionModel
    FrancGarr: OceanAbsorptionModel

class BC_Mode:
    MODE_R_Rigid: BC_Mode
    MODE_V_Vacuum: BC_Mode
    MODE_F_File: BC_Mode
    MODE_A_Half_space: BC_Mode
    MODE_G_Grain: BC_Mode
    MODE_P_Precomputed: BC_Mode

class Source_Mode:
    MODE_R_Point: Source_Mode
    MODE_X_Line: Source_Mode

class Grid_Mode:
    MODE_R_Rectangular: Grid_Mode
    MODE_I_Irregular: Grid_Mode

class Run_Mode:
    MODE_M_Modes: Run_Mode
    MODE_F_Field: Run_Mode
    MODE_B_Both: Run_Mode

class CoherenceType:
    Coherent: CoherenceType
    Incoherent: CoherenceType

class ModeType:
    Adiabatic: ModeType
    Couple: ModeType

class Atten_Mode:
    attnUnit: AttenuationUnit
    absModel: OceanAbsorptionModel
    def __init__(self) -> None: ...

class HSInfo:
    alphaR: float
    alphaI: float
    betaR: float
    betaI: float
    beta: float
    ft: float
    cp: complex
    cs: complex
    rho: float
    Depth: float
    BC: BC_Mode
    def __init__(self) -> None: ...

class SSPLayer:
    npts: int
    nmesh: int
    beta: float
    ft: float
    sigma: float
    Material: Media_Mode
    z: np.ndarray
    rho: np.ndarray
    alphaR: np.ndarray
    alphaI: np.ndarray
    betaR: np.ndarray
    betaI: np.ndarray
    def __init__(self) -> None: ...

class Range_Independent_Area:
    SSPType: SSP_Mode
    layers: list[SSPLayer]
    HSTop: HSInfo
    HSBot: HSInfo
    Range: float
    def __init__(self) -> None: ...
    def addLayer(self, layer: SSPLayer) -> None: ...
    def clearLayer(self) -> None: ...
    def NMedia(self) -> int: ...
    def set_Bottom_Line(self, *args: Any) -> None: ...
    def set_Top_Line(self, *args: Any) -> None: ...
    def set_Bottom_type(self, mode: BC_Mode) -> None: ...
    def set_Top_type(self, mode: BC_Mode) -> None: ...

class ReflectionCoef:
    theta: float
    R: float
    phi: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theta: float, magnitude: float, phase: float) -> None: ...

class FieldSnapshot:
    @property
    def title(self) -> str: ...
    @property
    def frequency(self) -> float: ...
    @property
    def grid_type(self) -> Grid_Mode: ...
    @property
    def source_count(self) -> int: ...
    @property
    def range_count(self) -> int: ...
    @property
    def depth_count(self) -> int: ...
    @property
    def source_depths(self) -> np.ndarray: ...
    @property
    def receiver_ranges(self) -> np.ndarray: ...
    @property
    def receiver_depths(self) -> np.ndarray: ...
    @property
    def values(self) -> np.ndarray: ...

class ModeProfileSnapshot:
    @property
    def profile_range(self) -> float: ...
    @property
    def depth(self) -> np.ndarray: ...
    @property
    def wavenumbers(self) -> np.ndarray: ...
    @property
    def group_velocity(self) -> np.ndarray: ...
    @property
    def mode_shapes(self) -> np.ndarray: ...

class Interface:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, pool: ThreadPool) -> None: ...
    def setNumThreads(self, count: int) -> None: ...
    def setThreadPool(self, pool: ThreadPool) -> None: ...
    def getNumThreads(self) -> int: ...
    def getHardwareThreads(self) -> int: ...
    def from_env(self, path: str) -> bool: ...
    def from_json(self, path: str) -> bool: ...
    def to_json(self, path: str) -> bool: ...
    def to_json_string(self) -> str: ...
    def set_Title(self, title: str) -> None: ...
    def set_Freq(self, frequency: float) -> None: ...
    def set_freqvec(self, frequencies: np.ndarray) -> None: ...
    def set_SSP(self, areas: Sequence[Range_Independent_Area]) -> None: ...
    def set_AttenUnit(self, mode: Atten_Mode) -> None: ...
    def set_Sz(self, *args: Any) -> None: ...
    def set_Rr(self, *args: Any) -> None: ...
    def set_Rz(self, *args: Any) -> None: ...
    def set_Ro(self, *args: Any) -> None: ...
    def set_RProf(self, *args: Any) -> None: ...
    def set_MLimit(self, limit: int) -> None: ...
    def set_cPhase(self, low: float, high: float) -> None: ...
    def set_GridType(self, mode: Grid_Mode) -> None: ...
    def set_Rmax(self, value: float) -> None: ...
    def set_SourceType(self, mode: Source_Mode) -> None: ...
    def set_RunMode(self, mode: Run_Mode) -> None: ...
    def set_CoherenceType(self, mode: CoherenceType) -> None: ...
    def set_ModeType(self, mode: ModeType) -> None: ...
    def set_Velocity_enable(self, enabled: bool) -> None: ...
    def set_ReflCoef_Top(self, coefficients: Sequence[ReflectionCoef]) -> None: ...
    def set_ReflCoef_Bottom(self, coefficients: Sequence[ReflectionCoef]) -> None: ...
    def set_SBP(self, pattern: np.ndarray, angles: np.ndarray) -> None: ...
    def run(self) -> None: ...
    def runEigen(self) -> None: ...
    def runField(self) -> None: ...
    def clearResults(self) -> None: ...
    def free(self) -> None: ...
    def export_result(self, path: str) -> None: ...
    def export_mod(self, path: str) -> None: ...
    def export_shd(self, path: str, data_type: int) -> None: ...
    def get_pressure(self) -> np.ndarray: ...
    def get_vertical_velocity(self) -> np.ndarray: ...
    def get_horizontal_velocity(self) -> np.ndarray: ...
    def get_pressure_snapshot(self) -> FieldSnapshot: ...
    def get_vertical_velocity_snapshot(self) -> FieldSnapshot: ...
    def get_horizontal_velocity_snapshot(self) -> FieldSnapshot: ...
    def get_modes(self) -> list[ModeProfileSnapshot]: ...
